import Context from './context'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: any) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Context {...props}>
          {props.children}
        </Context>
      </body>
    </html>
  )
}
